version: '3'

services:
  parla-react:
    image: "${PARLA_REACT_IMAGE}"
    container_name: parla-react
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:parla.${ARLA_GROUP_ENDPOINT}"
      - "traefik.frontend.port=80"
    expose:
      - 80

networks:
  web:
    external:
      name: web