version: '3'

services:
  parla-api:
    image: "${PARLA_API_IMAGE}"
    container_name: parla-api
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.frontend.rule=Host:${PARLA_API_ENDPOINT}"
      - "traefik.frontend.port=3000"
    expose:
      - 3000

networks:
  web:
    external:
      name: web