version: '3'

services:
  parla-react:
    image: "${PARLA_REACT_IMAGE}"
    container_name: parla-react
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:parla.${ARLA_GROUP_ENDPOINT}"
      - "traefik.frontend.port=80"
    expose:
      - 80
  hike-api:
    image: "${HIKE_API_IMAGE}"
    container_name: hike-api
    env_file:
      - db.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:hikes.${ARLA_GROUP_ENDPOINT}"
      - "traefik.frontend.port=3000"
    expose:
      - 3000
networks:
  web:
    external:
      name: web
