name: Parla CD

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build hiking API
      run: |
       source variables.env
       docker build -t $PARLA_API_IMAGE api/
       docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
       docker push $PARLA_API_IMAGE
    - name: Build parla react app
      run: |
       docker build -t $PARLA_REACT_IMAGE react-app/
       docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
       docker push $PARLA_REACT_IMAGE

  deploy:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@master
    - name: Send latest deployment files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USET }}
        password: ${{ secrets.SSH_KEY }}
        source: "docker-compose.yml,variables.env"
        target: "parla/"
    - name: Deploy via docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
          cd parla/
          source variables.env
          docker-compose pull
          docker-compose down
          docker-compose up -d
